cat mycert.yaml 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-grp.soat.work
  namespace: default
spec:
  commonName: k8s-grp.soat.work
  secretName: scw-k8s-cert
  dnsNames:
    - k8s-grp.soat.work
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
