apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grp0.soat.work
  namespace: default
spec:
  commonName: grp0.soat.work
  secretName: scw-k8s-cert
  dnsNames:
    - grp0.soat.work
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
