cat mycert.yaml 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grp<GRP>.soat.work
  namespace: default
spec:
  commonName: grp<GRP>.soat.work
  secretName: scw-k8s-cert
  dnsNames:
    - grp<GRP>.soat.work
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
