wordpressBlogName: "Mon test de Helm Chart"
persistence:
  size: 3Gi
service:
  type: ClusterIP
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: grp<GRP>.soat.work
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
wordpressPlugins: 
  - akismet
