wordpressBlogName: "Test de Helm Chart Sept 2024"
persistence:
  size: 3Gi
service:
  type: ClusterIP
ingress:
  enabled: true
  ingressClassName: traefik
  hostname: k8s-<GRP>.soat.work
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
wordpressPlugins: 
  - akismet
